name: lab
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.1
  http: ^1.1.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/Logo360.png
    - assets/images/logos/Logo360Dark.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
          weight: 300
